#!/bin/sh

# Define Functions

# Install Dependency Software And Libraries
function INSTALL_DEPENDENCY() {
	yum -y update
	yum -y groupinstall "Development Tools"
	yum -y groupinstall "MySQL Database server"
	yum -y install python-devel python-pip libxml2-devel libxslt-devel MySQL-python
	yum -y install rabbitmq-server bridge-utils iscsi-initiator-utils scsi-target-utils
	yum -y install virt-manager libvirt qemu-kvm virt-viewer
}

# Turn Off Selinux
function DISABLE_SELINUX() {
	setenforce 0
	sed -i '/^SELINUX=/s/enforcing/disabled/g' /etc/selinux/config
}

# Install RDO and EPEL REPO
function INSTALL_RDO_EPEL() {
	RHEL6_EPEL_RPM="http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
	RHEL6_EPEL_ID="epel"
	if ! yum repolist enabled $RHEL6_EPEL_RPM | grep -q $RHEL6_EPEL_ID; then
		wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
		rpm -ivh epel-release-6-8.noarch.rpm
		rm -f epel-release-6-8.noarch.rpm
	fi

	RHEL6_RDO_REPO_RPM="http://rdo.fedorapeople.org/openstack/openstack-grizzly/rdo-release-grizzly-3.noarch.rpm"
	RHEL6_RDO_REPO_ID="openstack-grizzly"
	if ! yum repolist enabled $RHEL6_RDO_REPO_ID | grep -q $RHEL6_RDO_REPO_ID; then
		wget http://rdo.fedorapeople.org/openstack/openstack-grizzly/rdo-release-grizzly-3.noarch.rpm
		rpm -ivh rdo-release-grizzly-3.noarch.rpm
		rm -f rdo-release-grizzly-3.noarch.rpm
	fi
}

# Download Openstack Source (Projects: 32)
function DOWNLOAD() {
	GIT_BASE="https://github.com"
	# Keystone
	KEYSTONE_REPO="$GIT_BASE/openstack/keystone.git"
	git clone $KEYSTONE_REPO
	KEYSTONECLIENT_REPO="$GIT_BASE/openstack/python-keystoneclient.git"
	git clone $KEYSTONECLIENT_REPO
	# Glance
	GLANCE_REPO="$GIT_BASE/openstack/glance.git"
	git clone $GLANCE_REPO
	GLANCECLIENT_REPO="$GIT_BASE/openstack/python-glanceclient.git"
	git clone $GLANCECLIENT_REPO
	# Cinder
	CINDER_REPO="$GIT_BASE/openstack/cinder.git"
	git clone $CINDER_REPO
	CINDERCLIENT_REPO="$GIT_BASE/openstack/python-cinderclient.git"
	git clone $CINDERCLIENT_REPO
	# Nova
	NOVA_REPO="$GIT_BASE/openstack/nova.git"
	git clone $NOVA_REPO
	NOVACLIENT_REPO="$GIT_BASE/openstack/python-novaclient.git"
	git clone $NOVACLIENT_REPO
	# Horizon
	HORIZON_REPO="$GIT_BASE/openstack/horizon.git"
	git clone $HORIZON_REPO
	# Neutron
	NEUTRON_REPO="$GIT_BASE/openstack/neutron.git"
	git clone $NEUTRON_REPO
	NEUTRONCLIENT_REPO="$GIT_BASE/openstack/python-neutronclient.git"
	git clone $NEUTRONCLIENT_REPO
	# Swift
	SWIFT_REPO="$GIT_BASE/openstack/swift.git"
	git clone $SWIFT_REPO
	SWIFT3_REPO="$GIT_BASE/fujita/swift3.git"
	git clone $SWIFT3_REPO
	SWIFTCLIENT_REPO="$GIT_BASE/openstack/python-swiftclient.git"
	git clone $SWIFTCLIENT_REPO
	# NoVNC
	NOVNC_REPO="$GIT_BASE/kanaka/noVNC.git"
	git clone $NOVNC_REPO
	# Ceilometer
	CEILOMETER_REPO="$GIT_BASE/openstack/ceilometer.git"
	git clone $CEILOMETER_REPO
	CEILOMETERCLIENT_REPO="$GIT_BASE/openstack/python-ceilometerclient.git"
	git clone $CEILOMETERCLIENT_REPO
	# Heat
	HEAT_REPO="$GIT_BASE/openstack/heat.git"
	git clone $HEAT_REPO
	HEATCLIENT_REPO="$GIT_BASE/openstack/python-heatclient.git"
	git clone $HEATCLIENT_REPO	
	# Ironic
	IRONIC_REPO="$GIT_BASE/openstack/ironic.git"
	git clone $IRONIC_REPO
	# Openstack Client
	OPENSTACKCLIENT_REPO="$GIT_BASE/openstack/python-openstackclient.git"
	git clone $OPENSTACKCLIENT_REPO
	# oslo.config
	OSLOCFG_REPO="$GIT_BASE/openstack/oslo.config.git"
	git clone $OSLOCFG_REPO
	# oslo.messaging
	OSLOMSG_REPO="$GIT_BASE/openstack/oslo.messaging.git"
	git clone $OSLOMSG_REPO
	# consolidated openstack requirements	
	REQUIREMENTS_REPO="$GIT_BASE/openstack/requirements.git"
	git clone $REQUIREMENTS_REPO
	# Tempest test suite	
	TEMPEST_REPO="$GIT_BASE/openstack/tempest.git"
	git clone $TEMPEST_REPO
	# bm_poseur
	# Used to simulate a hardware environment for baremetal
	BM_POSEUR_REPO="$GIT_BASE/tripleo/bm_poseur.git"
	git clone $BM_POSEUR_REPO
	# ryu service
	RYU_REPO="$GIT_BASE/osrg/ryu.git"
	git clone $RYU_REPO
	# a websockets/html5 or flash powered SPICE console for vm instances
	SPICE_REPO="http://anongit.freedesktop.org/git/spice/spice-html5.git"
	git clone $SPICE_REPO
	# Trove
	TROVE_REPO="$GIT_BASE/openstack/trove.git"
	git clone $TROVE_REPO
	TROVECLIENT_REPO="$GIT_BASE/openstack/python-troveclient.git"
	git clone $TROVECLIENT_REPO	
}

